language: julia

julia:
  - 1

os:
  - linux
  - osx
  - windows
  
branches:
  only:
  - master
  - /v\d+\.\d+[a-z]/

jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
